// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfcp11Qd1zdoBz4dWnKzTZ4NA0BJ0mwzY',
    appId: '1:130524301296:web:8a37f61d588cd2f2e3ff35',
    messagingSenderId: '130524301296',
    projectId: 'lazaaaaaaa-9112b',
    authDomain: 'lazaaaaaaa-9112b.firebaseapp.com',
    storageBucket: 'lazaaaaaaa-9112b.firebasestorage.app',
    measurementId: 'G-WTXJQRQY47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrEQcwyZDm2Fsy1J868VPhmjCcJ7kEI8',
    appId: '1:130524301296:android:1c64f692a0385bdee3ff35',
    messagingSenderId: '130524301296',
    projectId: 'lazaaaaaaa-9112b',
    storageBucket: 'lazaaaaaaa-9112b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMUYZhlgrWyJlONRkZ_OCAJzoJD9KZ9s',
    appId: '1:130524301296:ios:22f5c11e78face8be3ff35',
    messagingSenderId: '130524301296',
    projectId: 'lazaaaaaaa-9112b',
    storageBucket: 'lazaaaaaaa-9112b.firebasestorage.app',
    iosBundleId: 'com.example.lazaaaaaaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMUYZhlgrWyJlONRkZ_OCAJzoJD9KZ9s',
    appId: '1:130524301296:ios:22f5c11e78face8be3ff35',
    messagingSenderId: '130524301296',
    projectId: 'lazaaaaaaa-9112b',
    storageBucket: 'lazaaaaaaa-9112b.firebasestorage.app',
    iosBundleId: 'com.example.lazaaaaaaa',
  );
}
